repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-yaml
    # -   id: check-json
    # -   id: debug-statements
    # -   id: name-tests-test
    # -   id: requirements-txt-fixer
    # -   id: double-quote-string-fixer

-   repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
      language_version: python3.8

-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    - id: isort

-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
